### ISSUE TITLE
Cannot find name 'VideoFrame' error

### ISSUE THREAD

**Issue by mikeny07** [gpuweb/types#127]
I have a WebGPU project that runs fine using @webgpu/types version 0.1.31. However, when updating to 0.1.33, I got the following error when running the same project:

node_modules/@webgpu/types/dist/index.d.ts:83:7 - error TS2304: Cannot find name 'VideoFrame'.

83     | VideoFrame
         ~~~~~~~~~~

node_modules/@webgpu/types/dist/index.d.ts:807:7 - error TS2304: Cannot find name 'VideoFrame'.

807     | VideoFrame;
          ~~~~~~~~~~

The error seems nothing to do with my code. How to fix it?

**Comment by kainino0x** [comment]
Ah, I forgot about this problem when we landed the additional VideoFrame overload.
This requires `@types/dom-webcodecs`. Let try a fix for this.

**Comment by kainino0x** [comment]
@mikeny07 could you test if the PR #128 fixes this issue for you? I think you can test it out by replacing for example
`"@webgpu/types": "0.1.33",`
with
`"@webgpu/types": "kainino0x/types#cd1df383c20574709c80d18cb31d14f482bb5795",`

**Comment by mikeny07** [comment]
with:

"@webgpu/types": "kainino0x/types#cd1df383c20574709c80d18cb31d14f482bb5795",

I got more errors when running the project:

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:56:14 - error TS2304: Cannot find name 'AvcBitstreamFormat'.

56     format?: AvcBitstreamFormat | undefined;
                ~~~~~~~~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:74:11 - error TS2552: Cannot find name 'EncodedVideoChunkType'. Did you mean 'EncodedVideoChunk'?

74     type: EncodedVideoChunkType;
             ~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:266:13
    266 declare var EncodedVideoChunk: {
                    ~~~~~~~~~~~~~~~~~
    'EncodedVideoChunk' is declared here.

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:137:13 - error TS2304: Cannot find name 'AlphaOption'.

137     alpha?: AlphaOption | undefined;
                ~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:140:19 - error TS2304: Cannot find name 'VideoEncoderBitrateMode'.  

140     bitrateMode?: VideoEncoderBitrateMode | undefined;
                      ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:147:19 - error TS2304: Cannot find name 'LatencyMode'.

147     latencyMode?: LatencyMode | undefined;
                      ~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:173:13 - error TS2304: Cannot find name 'VideoPixelFormat'.

173     format: VideoPixelFormat;
                ~~~~~~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:185:13 - error TS2304: Cannot find name 'AlphaOption'.

185     alpha?: AlphaOption | undefined;
                ~~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:214:21 - error TS2304: Cannot find name 'CodecState'.

214     readonly state: CodecState;
                        ~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:231:21 - error TS2304: Cannot find name 'CodecState'.

231     readonly state: CodecState;
                        ~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:262:20 - error TS2552: Cannot find name 'EncodedVideoChunkType'. Did you mean 'EncodedVideoChunk'?

262     readonly type: EncodedVideoChunkType;
                       ~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:266:13
    266 declare var EncodedVideoChunk: {
                    ~~~~~~~~~~~~~~~~~
    'EncodedVideoChunk' is declared here.

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:329:21 - error TS2304: Cannot find name 'CodecState'.

329     readonly state: CodecState;
                        ~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:346:21 - error TS2304: Cannot find name 'CodecState'.

346     readonly state: CodecState;
                        ~~~~~~~~~~

node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:368:22 - error TS2304: Cannot find name 'VideoPixelFormat'.

368     readonly format: VideoPixelFormat | null;
                         ~~~~~~~~~~~~~~~~

Found 13 errors in the same file, starting at: node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:56

**Comment by kainino0x** [comment]
It appears that `@types/dom-webcodecs`>[0.1.6](https://www.unpkg.com/@types/dom-webcodecs@0.1.6/webcodecs.generated.d.ts) removed some definitions that have been merged in upstream TypeScript and therefore [require](https://github.com/microsoft/TypeScript/commit/bb566f997720926597fc0f680c8c5a24fd47f302) TypeScript >5.1.3.

It seems you can use this page to determine which version of the package to use for your version of TypeScript. I think you'll have to install that particular package version explicitly. I arbitrarily chose `^0.1.5` as the min version but I can probably loosen that to `^0.1.3`.

**Comment by kainino0x** [comment]
... this page: https://www.npmjs.com/package/@types/dom-webcodecs?activeTab=versions

**Comment by kainino0x** [comment]
Attempting this further, I don't think there's a way this package can express its dependency on `@types/dom-webcodecs` due to the complex relationship between those dependencies and TypeScript. TypeScript 5.1 actually includes WebCodecs upstream and doesn't need `@types/dom-webcodecs` anymore.

I'm adding tests/examples that make sure the types build and work in various typescript versions.

**Comment by kainino0x** [comment]
Please reopen this if the latest release 0.1.34 with the version-appropriate sibling dependency on `@types/dom-webcodecs` doesn't work for you.

**Comment by mikeny07** [comment]
using @webgpu/types 0.1.34 and typescript 4.6.3, I got the error:

Found 2 errors in the same file, starting at: node_modules/@webgpu/types/dist/index.d.ts:83

after updating typescript to 5.1.3, the project compiles and runs successfully without any error.
