### ISSUE TITLE
error TS2304: Cannot find name 'PredefinedColorSpace'

### ISSUE THREAD

**Issue by qjia7** [gpuweb/types#106]
After upgrading webgpu/types from `0.1.16` to `0.1.21`, I always meet below errors in PR [tfjs:6862](https://github.com/tensorflow/tfjs/pull/6862):
```
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [96m../node_modules/@webgpu/types/dist/index.d.ts[0m:[93m587[0m:[93m16[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m587[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m   [0m [91m               ~~~~~~~~~~~~~~~~~~~~[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [96m../node_modules/@webgpu/types/dist/index.d.ts[0m:[93m728[0m:[93m16[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m728[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m   [0m [91m               ~~~~~~~~~~~~~~~~~~~~[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [96m../node_modules/@webgpu/types/dist/index.d.ts[0m:[93m800[0m:[93m16[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m800[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": [7m   [0m [91m               ~~~~~~~~~~~~~~~~~~~~[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": Found 3 errors.
```

**Comment by qjia7** [comment]
It turns out after upgrading `typescript` to 4.8.4. The errors disappear.  So close this one.
